FROM node:20-slim

LABEL maintainer="Luiz Carlos"
LABEL email="argentinaluiz@gmail.com"
LABEL version="1.0.0"

RUN apt update -y && \
    apt install --no-install-recommends -y \
    openssl && \
    rm -rf /var/lib/apt/lists/*

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

RUN npm install && npm cache clean --force

COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]